### ISSUE TITLE
MongoDB requires a filesystem that supports fsync()

### ISSUE THREAD

**Issue by msbeck** [astrostl/nrdev#10] opened 2018-02-14 18:24 UTC
https://docs.mongodb.com/manual/administration/production-notes/#kernel-and-file-systems

> IMPORTANT
> 
> MongoDB requires a filesystem that supports fsync() on directories. For example, HGFS and Virtual Box’s shared folders do not support this operation.
> 

How is this project getting around this?

When I run 

`mongod --dbpath ./data`

I get the following
```
vagrant@ubuntu-xenial:/vagrant/netrunner$ mongod --dbpath ./data
2018-02-14T18:25:06.515+0000 [initandlisten] MongoDB starting : pid=7704 port=27017 dbpath=./data 64-bit host=ubuntu-xenial
2018-02-14T18:25:06.516+0000 [initandlisten] db version v2.6.10
2018-02-14T18:25:06.516+0000 [initandlisten] git version: nogitversion
2018-02-14T18:25:06.516+0000 [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2018-02-14T18:25:06.516+0000 [initandlisten] build info: Linux lgw01-12 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 BOOST_LIB_VERSION=1_58
2018-02-14T18:25:06.516+0000 [initandlisten] allocator: tcmalloc
2018-02-14T18:25:06.516+0000 [initandlisten] options: { storage: { dbPath: "./data" } }
2018-02-14T18:25:06.526+0000 [initandlisten] 	WARNING: This file system is not supported. For further information see:
2018-02-14T18:25:06.527+0000 [initandlisten] 			http://dochub.mongodb.org/core/unsupported-filesystems
2018-02-14T18:25:06.527+0000 [initandlisten] 		Please notify MongoDB, Inc. if an unlisted filesystem generated this warning.
2018-02-14T18:25:06.536+0000 [initandlisten] journal dir=./data/journal
2018-02-14T18:25:06.539+0000 [initandlisten] recover : no journal files present, no recovery needed
2018-02-14T18:25:06.585+0000 [initandlisten] ERROR:   mmap() failed for ./data/local.ns len:16777216 errno:22 Invalid argument
2018-02-14T18:25:06.585+0000 [initandlisten] error couldn't open file ./data/local.ns terminating
2018-02-14T18:25:06.585+0000 [initandlisten] dbexit: 
2018-02-14T18:25:06.586+0000 [initandlisten] shutdown: going to close listening sockets...
2018-02-14T18:25:06.586+0000 [initandlisten] shutdown: going to flush diaglog...
2018-02-14T18:25:06.586+0000 [initandlisten] shutdown: going to close sockets...
2018-02-14T18:25:06.586+0000 [initandlisten] shutdown: waiting for fs preallocator...
2018-02-14T18:25:06.586+0000 [initandlisten] shutdown: lock for final commit...
2018-02-14T18:25:06.586+0000 [initandlisten] shutdown: final commit...
2018-02-14T18:25:06.586+0000 [initandlisten] shutdown: closing all files...
2018-02-14T18:25:06.586+0000 [initandlisten] closeAllFiles() finished
2018-02-14T18:25:06.586+0000 [initandlisten] journalCleanup...
2018-02-14T18:25:06.587+0000 [initandlisten] removeJournalFiles
2018-02-14T18:25:06.594+0000 [initandlisten] shutdown: removing fs lock...
2018-02-14T18:25:06.595+0000 [initandlisten] dbexit: really exiting now
```

I still seem to be able to play the game and build decks and so forth so I'm assuming this is ran elsewhere.

**Comment by msbeck** [comment] 2018-02-14 18:52
Wondering if this has anything to do with why lein figwheel is not connecting for me 

https://github.com/mtgred/netrunner/issues/3083

**Comment by astrostl** [comment] 2018-02-15 01:58
MongoDB is using `/var/lib/mongodb` (non-shared) as its data dir.

**Comment by msbeck** [comment] 2018-02-15 03:07
Ah, so not the ./data that is used with the normal repo setup?

**Comment by astrostl** [comment] 2018-02-15 03:08
Not sure to what you're referring by "normal repo setup"

**Comment by msbeck** [comment] 2018-02-15 03:11
My apologies, I mean that if you run the Netrunner project without nrdev
and virtual machines and whatnot, the --dbpath is ./data from what I
understand.

**Comment by astrostl** [comment] 2018-02-15 03:13
That makes sense to me for local, non-administrator, cross-platform development. Here MongoDB is "properly" installed as a packaged service, so it's just using the default service directory. All of which is only to say, the MongoDB-on-shared factor shouldn't be in play here, because MongoDB isn't on a shared dir.

**Comment by astrostl** [comment] 2018-02-15 03:15
Glancing at the other ticket - with "nrdev" 1042 is bound by the full-blown Java service. If you want to stop it and run from the REPL, I would try a `sudo service netrunner stop` prior to running it. I think that's the one binding to 1042.

**Comment by msbeck** [comment] 2018-02-15 03:16
Ok, I'm just curious because I was launching mongod with the --dbpath
./data but I'm learning here that in the nrdev project I need to instead
use var/lib/mongodb.

Is that correct?

On Feb 14, 2018 9:13 PM, "Justin Honold" <notifications@github.com> wrote:

That makes sense to me for local, non-administrator, cross-platform
development. Here MongoDB is "properly" installed as a packaged service, so
it's just using the default service directory. All of which is only to say,
the MongoDB-on-shared factor shouldn't be in play here, because MongoDB
isn't on a shared dir.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/astrostl/nrdev/issues/10#issuecomment-365814518>, or mute
the thread

**Comment by astrostl** [comment] 2018-02-15 03:17
MongoDB is installed and configured to start as a service automatically, so there should be no need to issue any MongoDB commands at all - it's always running, already.

**Comment by msbeck** [comment] 2018-02-15 03:41
Ok, great. I didn't understand the full scope of what nrdev did and what
I'd still need to do from the Development Guide (
https://github.com/mtgred/netrunner/wiki/Getting-Started-with-Development)
in the original repo.

Does this also auto compile and deploy everything live like lein figwheel
does in Tips and Tricks (
https://github.com/mtgred/netrunner/wiki/Development-Tips-and-Tricks)?

**Comment by astrostl** [comment] 2018-02-18 23:17
Those tips are all based on using the REPL, not starting a Java server.

Would consider cutting over to the former if that's what you/others prefer.

**Comment by astrostl** [comment] 2018-03-03 19:53
Closing due to non-activity and "working as designed" in server, rather than REPL, mode. Feel free to reopen or continue convo as desired!

**Closed as completed by astrostl** 2018-03-03 19:53 UTC
